/** English UI phrases → Russian (locale ru). No faux-Cyrillic brand transliteration. */
export const RU_STRING_REPLACEMENTS: [string, string][] = [
  ['Reqcore', 'Реккор'],
  ['reqcore-demo', 'демо-реккор'],
  ['Draft', 'Черновик'],
  ['draft', 'черновик'],
  ['DRAFT', 'ЧЕРНОВИК'],
  ['REQCORE', 'РЕККОР'],
  ['demo@reqcore.com', 'демо@реккор.ком'],
  ['Email', 'Почта'],
  ['Demo Recruiter', 'Демо Рекрутер'],
  ['Referral', 'Рекомендация'],
  ['Career Site', 'Карьерный сайт'],
  ['Event', 'Мероприятие'],
  ['Agency', 'Агентство'],
  ['Direct', 'Прямой переход'],
  ['Custom', 'Свой канал'],
  ['Other', 'Другое'],
  ['Welcome to Reqcore', 'Добро пожаловать в Реккор'],
  ['AI Analysis — Reqcore', 'ИИ-анализ — Реккор'],
  ['AI Analysis', 'ИИ-анализ'],
  ['AI analysis', 'ИИ-анализ'],
  ['Overview of AI scoring runs and token usage', 'Обзор запусков ИИ-оценки и расхода токенов'],
  ['Failed to load AI analysis data.', 'Не удалось загрузить данные ИИ-анализа.'],
  ['No AI analysis yet', 'ИИ-анализа пока нет'],
  ['Configure your AI provider in Settings and set up scoring criteria on a job to start analyzing candidates.', 'Настройте провайдера ИИ в настройках и критерии оценки на вакансии, чтобы начать анализ кандидатов.'],
  ['Total Runs', 'Всего запусков'],
  ['Success Rate', 'Успешность'],
  ['Prompt Tokens', 'Токены запроса'],
  ['Completion Tokens', 'Токены ответа'],
  ['Total Cost', 'Общая стоимость'],
  ['Set pricing to track costs', 'Укажите цены для учёта затрат'],
  ['Usage — Last 30 Days', 'Использование — последние 30 дней'],
  ['Runs per Day', 'Запусков в день'],
  ['Model Breakdown', 'Разбивка по моделям'],
  ['Provider', 'Провайдер'],
  ['Runs', 'Запуски'],
  ['Cost', 'Стоимость'],
  ['Recent Runs', 'Недавние запуски'],
  ['completed', 'завершён'],
  ['failed', 'ошибка'],
  ['pending', 'ожидание'],
  ['Overview', 'Обзор'],
  ['Tracking Links', 'Ссылки отслеживания'],
  ['Attribution Log', 'Журнал атрибуции'],
  ['Tracked', 'Отслежено'],
  ['Attribution', 'Атрибуция'],
  ['Active Links', 'Активные ссылки'],
  ['Untracked', 'Без отслеживания'],
  ['Without attribution', 'Без атрибуции'],
  ['All time', 'Всё время'],
  ['All jobs', 'Все вакансии'],
  ['New Link', 'Новая ссылка'],
  ['Applications by Source', 'Отклики по источникам'],
  ['Conversion by Source', 'Конверсия по источникам'],
  ['Hire Rate', 'Доля найма'],
  ['Top Links', 'Топ ссылок'],
  ['View all', 'Смотреть все'],
  ['clicks', 'клики'],
  ['apps', 'отклики'],
  ['Loading pipeline…', 'Загрузка воронки…'],
  ['Job not found or failed to load.', 'Вакансия не найдена или не загрузилась.'],
  ['Back to Jobs', 'Назад к вакансиям'],
  ['Newest first', 'Сначала новые'],
  ['Highest score', 'Высший балл'],
  ['Scheduled', 'Запланировано'],
  ['No score', 'Без оценки'],
  ['Clear filters', 'Сбросить фильтры'],
  ['Properties', 'Свойства'],
  ['Reject', 'Отклонить'],
  ['Re-open', 'Вернуть'],
  ['Run Analysis', 'Запустить анализ'],
  ['High', 'Высокий'],
  ['Medium', 'Средний'],
  ['Low', 'Низкий'],
  ['My Jobs — Reqcore', 'Мои вакансии — Реккор'],
  ['Pipeline — Reqcore', 'Воронка — Реккор'],
  ['Organization Settings — Reqcore', 'Настройки организации — Реккор'],
  ['Team Members — Reqcore', 'Участники — Реккор'],
  ['AI Configuration — Reqcore', 'Настройка ИИ — Реккор'],
  ['Localization Settings — Reqcore', 'Локализация — Реккор'],
  ['Integrations — Reqcore', 'Интеграции — Реккор'],
  ['Account Settings — Reqcore', 'Аккаунт — Реккор'],
  ['Single Sign-On — Reqcore', 'Единый вход — Реккор'],
  ['Timeline — Reqcore', 'Хронология — Реккор'],
  ['Forgot Password — Reqcore', 'Восстановление пароля — Реккор'],
  ['Reset Password — Reqcore', 'Новый пароль — Реккор'],
  ['Open Positions', 'Открытые вакансии'],
  ['Loading positions…', 'Загрузка вакансий…'],
  ['No open positions', 'Нет открытых вакансий'],
  ['Previous', 'Назад'],
  ['Next', 'Далее'],
  ['All types', 'Все типы'],
  ['All Jobs', 'Все вакансии'],
  ['Get Started', 'Начать'],
  ['Switching…', 'Переключение…'],
  ['+ Create organization', '+ Создать организацию'],
  ['Setting up your workspace…', 'Настройка рабочего пространства…'],
  ["You're in!", 'Готово!'],
  ['Select an organization', 'Выберите организацию'],
  ['Create your organization', 'Создайте организацию'],
  ['Organization name is required.', 'Укажите название организации.'],
  ['Join', 'Вступить'],
  ['Send join request', 'Отправить запрос'],
  ['Paste invite link or code', 'Вставьте ссылку или код приглашения'],
  ['No organizations found', 'Организации не найдены'],
  ['Open Jobs', 'Открытые вакансии'],
  ['To Review', 'На проверку'],
  ['Needs attention', 'Требует внимания'],
  ['Hiring Pipeline', 'Воронка подбора'],
  ['Talent pool', 'Пул кандидатов'],
  ['Phone', 'Телефон'],
  ['Video', 'Видео'],
  ['In-person', 'Очно'],
  ['Tomorrow', 'Завтра'],
  ['Just now', 'Только что'],
  ['Retry', 'Повторить'],
  ['Cancel', 'Отмена'],
  ['Create Link', 'Создать ссылку'],
  ['Create Tracking Link', 'Создать ссылку отслеживания'],
  ['Link Name', 'Название ссылки'],
  ['Source Channel', 'Канал'],
  ['Scope to Job', 'Привязать к вакансии'],
  ['optional', 'необязательно'],
  ['UTM Parameters (optional)', 'Параметры UTM (необязательно)'],
  ['Delete Tracking Link?', 'Удалить ссылку?'],
  ['Filtered by:', 'Фильтр:'],
  ['Cover Letter', 'Сопроводительное'],
  ['Resume', 'Резюме'],
  ['or continue with email', 'или войти по почте'],
  ['Beta', 'Бета'],
  ['Continue with', 'Продолжить с'],
  ['Redirecting to your IdP…', 'Перенаправление на IdP…'],
  ['All fields are required.', 'Заполните все поля.'],
  ['Passwords do not match.', 'Пароли не совпадают.'],
  ['Reset your password', 'Сброс пароля'],
  ['Weak', 'Слабый'],
  ['Fair', 'Средний'],
  ['Too short', 'Слишком короткий'],
  ['Team members', 'Участники команды'],
  ['Invite member', 'Пригласить'],
  ['Save changes', 'Сохранить изменения'],
  ['Danger zone', 'Опасная зона'],
  ['Permanently delete', 'Удалить навсегда'],
  ['Default', 'По умолчанию'],
  ['Analyzing…', 'Анализ…'],
  ['Analysis failed', 'Анализ не выполнен'],
  ['Candidate scored', 'Кандидат оценён'],
  ['Go to AI Settings', 'Перейти в настройки ИИ'],
  ['Scoring failed', 'Оценка не выполнена'],
  ['Failed to update status', 'Не удалось обновить статус'],
  ['Failed to create link', 'Не удалось создать ссылку'],
  ['Failed to delete', 'Не удалось удалить'],
  ['Creating…', 'Создание…'],
  ['Job Boards', 'Доски вакансий'],
  ['Social Media', 'Соцсети'],
  ['Name', 'Название'],
  ['Source', 'Источник'],
  ['Clicks', 'Клики'],
  ['Apps', 'Отклики'],
  ['Status', 'Статус'],
  ['Active', 'Активна'],
  ['Inactive', 'Неактивна'],
  ['Copy', 'Копировать'],
  ['Delete', 'Удалить'],
  ['Confirm', 'Подтвердить'],
  ['Open-source', 'Открытый код'],
  ['applicant tracking', 'подбор кандидатов'],
  ['slug', 'идентификатор'],
  ['IdP', 'ИдП'],
  ['utm_source', 'утм_источник'],
  ['utm_medium', 'утм_канал'],
  ['utm_campaign', 'утм_кампания'],
  ['CVR', 'КВО'],
]
